valor=input('Digite um valor qualquer: ')
print(type(valor))
print('Seu valor é alfa numerico?', valor.isalnum())
print('Seu valor é do alfabeto?', valor.isalpha())
print('Seu valor está todo em minusculo?', valor.islower())
print('Seu valor está todo em maiusculo?', valor.isupper())
print('Seu valor so tem espaços?', valor.isspace())
print('Seu valor é numerico?', valor.isnumeric())
print('Está capitalizada?', valor.istitle())
